on:
  pull_request:
    branches: [ master ]
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:
      - name: "setup python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
        
      - name: "install python packages"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: run resource config sync
        run: python3 scripts/resource_config/main_resource_sync.py
